import { Inter } from 'next/font/google'
import './globals.css'
import 'remixicon/fonts/remixicon.css'
import Footer from '@/components/footer/Footer'
import { NextAuthProvider } from './Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className='app-main'>{children}</div>
          {/* <Footer /> */}
        </NextAuthProvider>

      </body>
    </html>
  )
}
